### PR TITLE
[simd] Sync integer min/max tests from simd repo

### PR DESCRIPTION
**Pull request by Honry**
Pull tests from PR https://github.com/WebAssembly/simd/pull/166 and commit https://github.com/WebAssembly/simd/pull/163/commits/5420581586314b202e585bd850d16a2f3405e312

### CODE REVIEW

**Comment by Honry** [comment]
@AndrewScheidecker, PTAL, thanks!

**Comment by AndrewScheidecker** [comment]
Can you update the `CMakeLists.txt` for the new filenames?

**Comment by Honry** [comment]
Oops, my bad, updated.

**Comment by AndrewScheidecker** [comment]
Thanks!

**Pull request merged**
