### PR TITLE
[simd] Update simd/simd_const.wast

### PR DESCRIPTION
**Pull request by Honry**
Since simd opcode has been renumbered
at https://github.com/WebAssembly/simd/pull/209

### CODE REVIEW

**Comment by Honry** [comment]
@AndrewScheidecker, @tlively, PTAL, thanks!

**Comment by tlively** [comment]
lgtm 👍

**Comment by AndrewScheidecker** [comment]
Thanks @Honry, but I already have these changes in https://github.com/WAVM/WAVM/tree/simd-opcode-renumbering, along with renumbering the opcodes in the C++ code. If the renumbering is finalized now, I'll look at merging that branch to main.

**Comment by Honry** [comment]
@AndrewScheidecker, never mind, I will close it.

**Comment by AndrewScheidecker** [comment]
@Honry FYI I merged the branch with the renumbering to master.

**Pull request closed without merging**
