### PR TITLE
[simd] Add spec tests for integer min/max ops

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@AndrewScheidecker, what's your plan on implementing integer min/max ops for WAVM?

**Comment by AndrewScheidecker** [comment]
Whoops, I missed that those were added. I've now implemented them in https://github.com/WAVM/WAVM/commit/4bf21331b4bbd43a918073592f4cc45f82789513, please rebase on that and see how it works.

**Comment by Honry** [comment]
Awesome! I am working on it.

**Comment by Honry** [comment]
@AndrewScheidecker, following tests fail because i64x2 min/max ops are treated as valid ops in WAVM.

```
(assert_malformed (module quote "(memory 1) (func (result v128) (i64x2.min_s (v128.const i32x4 0 0 0 0) (v128.const i32x4 1 1 1 1)))") "unknown operator")
(assert_malformed (module quote "(memory 1) (func (result v128) (i64x2.min_u (v128.const i32x4 0 0 0 0) (v128.const i32x4 1 1 1 1)))") "unknown operator")
(assert_malformed (module quote "(memory 1) (func (result v128) (i64x2.max_s (v128.const i32x4 0 0 0 0) (v128.const i32x4 1 1 1 1)))") "unknown operator")
(assert_malformed (module quote "(memory 1) (func (result v128) (i64x2.max_u (v128.const i32x4 0 0 0 0) (v128.const i32x4 1 1 1 1)))") "unknown operator")
```

**Comment by AndrewScheidecker** [comment]
I've removed the `i64x2` instructions in https://github.com/WAVM/WAVM/commit/c1ebb05f0481a9a24ec3dadb4e8e58a6cc3a3884.

**Comment by Honry** [comment]
Thank you @AndrewScheidecker, I've rebased it and everything goes fine.

**Comment by AndrewScheidecker** [comment]
LGTM, thanks!

**Pull request merged**
