### PR TITLE
[simd] Add spec tests for comparison instructions

### PR DESCRIPTION
**Pull request by Honry**
Including equality, non-equality, less than, less than or equal,
greater than and greater than or equal.

Most of the major boundary values and other special values testing
are referenced from f32_cmp.wast and i32.wast files in
https://github.com/WebAssembly/spec/tree/master/test/core

### CODE REVIEW

**Comment by Honry** [comment]
There are amounts of tests on major boundary values and all special values, most of which are generated by script, sorry for the inconvenient on review.

**Comment by Honry** [comment]
@AndrewScheidecker, @tlively, @arunetm, PTAL. thanks!

**Comment by AndrewScheidecker** [comment]
It would be nice to have the scripts used to generate these tests as well.

For example, the bulk-memory-operations proposal has some scripts in [test/meta](https://github.com/WebAssembly/bulk-memory-operations/tree/master/test/meta) that can be run to regenerate the test scripts.

**Comment by Honry** [comment]
> It would be nice to have the scripts used to generate these tests as well.

@AndrewScheidecker, I agree. :)

Currently my script is wrote in python and only support generating tests on major boundary values and all special values, as which is large in number and the content is very similar, that'd be more convenient to be generated by script.

I need time to process my script to support generating the rest tests, do you think I need to rewrite it to use JS? Which place you'd prefer to locate the script to?

**Comment by AndrewScheidecker** [comment]
> do you think I need to rewrite it to use JS?

No, I think Python is fine.

> Which place you'd prefer to locate the script to?

I guess `Test/spec/meta`, and that can be mapped to `test/meta` in the spec repo.

**Comment by Honry** [comment]
@AndrewScheidecker, sorry for the late response as I was busy on another stuff. I just submitted a rough generation script, PTAL. Thanks!

**Comment by AndrewScheidecker** [comment]
Thanks!

**Pull request merged**
