### PR TITLE
[simd] Add spec tests for arithmetic relevant instructions

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@AndrewScheidecker, tests for float-point arithmetic adopts `assert_return_canonical_nan_f32x4` at present, will update it if it's differ from the final solution.  PTAL. Thanks!

**Comment by AndrewScheidecker** [comment]
https://github.com/WAVM/WAVM/commit/e59418bac8915e308f2d8d080d699a2c1277cb77 adds the `assert_return_canonical_nan_f32x4` command. Can you please rebase this and see if it passes CI?

**Comment by Honry** [comment]
@AndrewScheidecker, yeah! It works well, thanks for your quick support!

**Comment by Honry** [comment]
Thank you for your review! @AndrewScheidecker

**Pull request merged**
